# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
      initrd = {
        availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "rtsx_pci_sdmmc" ];
        kernelModules = [ ];
        systemd.enable = true;
      };
      kernelModules = [ "kvm-amd" ];
      extraModulePackages = [ ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d56143e-c9f5-4de2-86be-3698d3af059c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8425bf0a-54d5-4569-9743-6f8ef748d951".device = "/dev/disk/by-uuid/8425bf0a-54d5-4569-9743-6f8ef748d951";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1C73-9E0C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ { device = "/var/swapfile"; size = 32*1024; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
