{ inputs, pkgs, ... }: {
  home.packages = with pkgs; [
    #firefox
    kdePackages.kate
    #cura
    #vscode
    qalculate-qt
    #octaveFull
    #octavePackages.symbolic
    #logisim-evolution
    #minecraft - marked as broken, refusing to evaluate
    #**steam
    #blender
    #epson-escpr2
    #printrun
    discord
    #google-chrome
    #thunderbird
    #onlyoffice-bin
    pdfarranger
    solaar
    #polychromatic
    #kitty
    #waybar
    #nwg-bar
    #nwg-look
    #nwg-panel
    #nwg-menu
    #nwg-hello
    #nwg-displays
    glib
    #ark
    #yofi
    #helix
    networkmanagerapplet
    #xdg-desktop-portal-gtk
    #xdg-desktop-portal-hyprland
    #meson
    #wayland-protocols
    #wayland-utils
    #wl-clipboard
    #wlroots
    #pavucontrol
    #dunst
    #polkit-kde-agent
    #nvidia-vaapi-driver
    #ffmpeg
    #nerdfonts
    fantasque-sans-mono
    nixfmt # ** -rfc-style
    #blueman
    pass-wayland
    gnupg
    passff-host
    #xfce.thunar
    walk
    #lunarvim
    #pyprland
    onedrive
    onedrivegui
    #virt-manager
    #freerdp
    appimage-run
    #apfs-fuse
    #nix-tree
    #obs-studio
    #obs-studio-plugins.droidcam-obs
    zed-editor
    libreoffice
    onlyoffice-desktopeditors
    #lutris
    #wine
    cosmic-store
    code-cursor
    opencode
    nil
    nixd
    inputs.zen-browser.packages."${pkgs.stdenv.hostPlatform.system}".default
  ];
}
